import DANH from './DANH';
import DBAN from './DBAN';
import DBANGGIA from './DBANGGIA';
import DBANGGIACHITIET from './DBANGGIACHITIET';
import DBANGGIATHEOBAN from './DBANGGIATHEOBAN';
import DBANGGIATHEOKHUVUC from './DBANGGIATHEOKHUVUC';
import DBANQUYEN from './DBANQUYEN';
import DBIEUTUONG from './DBIEUTUONG';
import DCALAMVIEC from './DCALAMVIEC';
import DCHITIEUCHITIET from './DCHITIEUCHITIET';
import DCHITIEUDOANHTHU from './DCHITIEUDOANHTHU';
import DCUAHANG from './DCUAHANG';
import DDINHLUONG from './DDINHLUONG';
import DDOITACKYGUI from './DDOITACKYGUI';
import DDONVITINH from './DDONVITINH';
import DDOTKHUYENMAI from './DDOTKHUYENMAI';
import DDOTKHUYENMAICHITIET from './DDOTKHUYENMAICHITIET';
import DGHICHUPHACHE from './DGHICHUPHACHE';
import DGIAMATHANG from './DGIAMATHANG';
import DGIAODIENTHAOTAC from './DGIAODIENTHAOTAC';
import DHANGSANXUAT from './DHANGSANXUAT';
import DKHACHHANG from './DKHACHHANG';
import DKHOHANG from './DKHOHANG';
import DKHUVUC from './DKHUVUC';
import DLOAIDO from './DLOAIDO';
import DLOAIHINHKHUYENMAI from './DLOAIHINHKHUYENMAI';
import DLOAIMATHANG from './DLOAIMATHANG';
import DLOAIPHONG from './DLOAIPHONG';
import DLOAIQUY from './DLOAIQUY';
import DLYDOHUY from './DLYDOHUY';
import DLYDOTHUCHI from './DLYDOTHUCHI';
import DLYDOTHUONGPHAT from './DLYDOTHUONGPHAT';
import DMATHANG from './DMATHANG';
import DMATHANGMACDINH from './DMATHANGMACDINH';
import DMATKHAUWIFI from './DMATKHAUWIFI';
import DMUCDICHDAT from './DMUCDICHDAT';
import DNHACUNGCAP from './DNHACUNGCAP';
import DNHANVIEN from './DNHANVIEN';
import DNHOMCHITIEUDOANHTHU from './DNHOMCHITIEUDOANHTHU';
import DNHOMHIENTHI from './DNHOMHIENTHI';
import DNHOMKHACHHANG from './DNHOMKHACHHANG';
import DNHOMMATHANG from './DNHOMMATHANG';
import DNHOMNHACUNGCAP from './DNHOMNHACUNGCAP';
import DNHOMTHETRATRUOC from './DNHOMTHETRATRUOC';
import DNHOMVOUCHER from './DNHOMVOUCHER';
import DNHOMWIFI from './DNHOMWIFI';
import DPHUONGTHUCDAT from './DPHUONGTHUCDAT';
import DTAIKHOANNGANHANG from './DTAIKHOANNGANHANG';
import DTHETRATRUOC from './DTHETRATRUOC';
import DTINHTHANH from './DTINHTHANH';
import DTKTHEOKHUVUC from './DTKTHEOKHUVUC';
import DTRANGTHAICHEBIEN from './DTRANGTHAICHEBIEN';
import DUNGDUNG from './DUNGDUNG';
import DVOUCHER from './DVOUCHER';
import SANALYSIS from './SANALYSIS';
import SCOLUMN from './SCOLUMN';
import SCONFIG from './SCONFIG';
import SCONFIGGROUP from './SCONFIGGROUP';
import SFORM from './SFORM';
import SFUNCTION from './SFUNCTION';
import SGRID from './SGRID';
import SGROUPROLE from './SGROUPROLE';
import SGROUPUSER from './SGROUPUSER';
import SIMAGE from './SIMAGE';
import SMENU from './SMENU';
import SQUICKNOTE from './SQUICKNOTE';
import SREPORT from './SREPORT';
import SREPORTROLE from './SREPORTROLE';
import SREPORTTEMPLATE from './SREPORTTEMPLATE';
import SSMSTEMPLATE from './SSMSTEMPLATE';
import STABLEDESC from './STABLEDESC';
import STEMPLATE from './STEMPLATE';
import SUSER from './SUSER';
import TBANGLUONG from './TBANGLUONG';
import TBANGLUONGCHITIET from './TBANGLUONGCHITIET';
import TBANGLUONGTONGHOP from './TBANGLUONGTONGHOP';
import TBAOGIA from './TBAOGIA';
import TBAOGIACHITIET from './TBAOGIACHITIET';
import TCHITIETTHANHTOAN from './TCHITIETTHANHTOAN';
import TDATHANG from './TDATHANG';
import TDATHANGCHITIET from './TDATHANGCHITIET';
import TDONHANG from './TDONHANG';
import TDONHANGCHITIET from './TDONHANGCHITIET';
import TDONHANGGIO from './TDONHANGGIO';
import TDONHANGHUY from './TDONHANGHUY';
import TDONHANGHUYCHITIET from './TDONHANGHUYCHITIET';
import TINCHEBIEN from './TINCHEBIEN';
import TLUUTAM from './TLUUTAM';
import TLUUTAMCHITIET from './TLUUTAMCHITIET';
import TLUUVET from './TLUUVET';
import TNGUOIDUNGTHEOCUAHANG from './TNGUOIDUNGTHEOCUAHANG';
import TSOHOADON from './TSOHOADON';
import TSOINCHEBIEN from './TSOINCHEBIEN';
import TSUACHUA from './TSUACHUA';
import TTANGGIAMDIEM from './TTANGGIAMDIEM';
import TTHUCHI from './TTHUCHI';
import TTHUONGPHAT from './TTHUONGPHAT';
import TVAORA from './TVAORA';

export {
    DANH,
    DBAN,
    DBANGGIA,
    DBANGGIACHITIET,
    DBANGGIATHEOBAN,
    DBANGGIATHEOKHUVUC,
    DBANQUYEN,
    DBIEUTUONG,
    DCALAMVIEC,
    DCHITIEUCHITIET,
    DCHITIEUDOANHTHU,
    DCUAHANG,
    DDINHLUONG,
    DDOITACKYGUI,
    DDONVITINH,
    DDOTKHUYENMAI,
    DDOTKHUYENMAICHITIET,
    DGHICHUPHACHE,
    DGIAMATHANG,
    DGIAODIENTHAOTAC,
    DHANGSANXUAT,
    DKHACHHANG,
    DKHOHANG,
    DKHUVUC,
    DLOAIDO,
    DLOAIHINHKHUYENMAI,
    DLOAIMATHANG,
    DLOAIPHONG,
    DLOAIQUY,
    DLYDOHUY,
    DLYDOTHUCHI,
    DLYDOTHUONGPHAT,
    DMATHANG,
    DMATHANGMACDINH,
    DMATKHAUWIFI,
    DMUCDICHDAT,
    DNHACUNGCAP,
    DNHANVIEN,
    DNHOMCHITIEUDOANHTHU,
    DNHOMHIENTHI,
    DNHOMKHACHHANG,
    DNHOMMATHANG,
    DNHOMNHACUNGCAP,
    DNHOMTHETRATRUOC,
    DNHOMVOUCHER,
    DNHOMWIFI,
    DPHUONGTHUCDAT,
    DTAIKHOANNGANHANG,
    DTHETRATRUOC,
    DTINHTHANH,
    DTKTHEOKHUVUC,
    DTRANGTHAICHEBIEN,
    DUNGDUNG,
    DVOUCHER,
    SANALYSIS,
    SCOLUMN,
    SCONFIG,
    SCONFIGGROUP,
    SFORM,
    SFUNCTION,
    SGRID,
    SGROUPROLE,
    SGROUPUSER,
    SIMAGE,
    SMENU,
    SQUICKNOTE,
    SREPORT,
    SREPORTROLE,
    SREPORTTEMPLATE,
    SSMSTEMPLATE,
    STABLEDESC,
    STEMPLATE,
    SUSER,
    TBANGLUONG,
    TBANGLUONGCHITIET,
    TBANGLUONGTONGHOP,
    TBAOGIA,
    TBAOGIACHITIET,
    TCHITIETTHANHTOAN,
    TDATHANG,
    TDATHANGCHITIET,
    TDONHANG,
    TDONHANGCHITIET,
    TDONHANGGIO,
    TDONHANGHUY,
    TDONHANGHUYCHITIET,
    TINCHEBIEN,
    TLUUTAM,
    TLUUTAMCHITIET,
    TLUUVET,
    TNGUOIDUNGTHEOCUAHANG,
    TSOHOADON,
    TSOINCHEBIEN,
    TSUACHUA,
    TTANGGIAMDIEM,
    TTHUCHI,
    TTHUONGPHAT,
    TVAORA,
};
