-- =====================================================
-- QUẢN LÝ BAR - SQL SERVER DATABASE (TỰ ĐỘNG SINH)
-- Tổng số bảng: 98
-- =====================================================

USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'QuanLyBar')
    DROP DATABASE QuanLyBar;
GO

CREATE DATABASE QuanLyBar;
GO

USE QuanLyBar;
GO

-- Bảng: DANH
CREATE TABLE DANH (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [ITALIC] BIT,
    [CONTROLLEVEL] NVARCHAR(MAX),
    [BOLD] BIT,
    [FONTSIZE] NVARCHAR(MAX),
    [VISIBLE] BIT,
    [FONTCOLOR] NVARCHAR(MAX),
    [CONTROLNAME] NVARCHAR(MAX),
    [UNDERLINE] BIT,
    [ICON] VARBINARY(MAX),
    [TRANSPARENT] BIT,
    [TEXTALIGN] NVARCHAR(MAX),
    [HASBORDER] BIT,
    [PARENTCONTROLNAME] NVARCHAR(MAX),
    [WIDTH] NVARCHAR(MAX),
    [ZINDEX] NVARCHAR(MAX),
    [FLAT] BIT,
    [REF1ID] INT,
    [REF2ID] INT,
    [FONTNAME] NVARCHAR(MAX),
    [IMAGEZOOM] NVARCHAR(MAX),
    [BORDERWIDTH] NVARCHAR(MAX),
    [BACKCOLOR] NVARCHAR(MAX),
    [HEIGHT] NVARCHAR(MAX),
    [ICONALIGN] NVARCHAR(MAX),
    [POSLEFT] NVARCHAR(MAX),
    [CUSTOMDATA1] NVARCHAR(MAX),
    [CUSTOMDATA2] NVARCHAR(MAX),
    [CUSTOMDATA3] NVARCHAR(MAX),
    [CONTROLTYPE] NVARCHAR(MAX),
    [POSTOP] NVARCHAR(MAX),
    [ANH] VARBINARY(MAX),
    [BUTTONSHAPE] NVARCHAR(MAX),
    [ROTATE] NVARCHAR(MAX),
    [NUMCHAIRS] NVARCHAR(MAX),
    [DKHUVUCID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT
);
GO

-- Bảng: DBAN
CREATE TABLE DBAN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [DKHUVUCID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DBANGGIAID] INT,
    [DONGIA] DECIMAL(18,2),
    [CACHTINHGIO] DATETIME,
    [DNHOMHIENTHIID] INT,
    [TIENMOBAN] DECIMAL(18,2),
    [DLOAIPHONGID] INT,
    [TDONHANGID] INT,
    [TRANGTHAI] NVARCHAR(MAX),
    [TAIKHOANGIU] NVARCHAR(MAX),
    [GIULUC] NVARCHAR(MAX),
    [IPCONGTAC] NVARCHAR(MAX),
    [ITALIC] BIT,
    [CONTROLLEVEL] NVARCHAR(MAX),
    [FONTSIZE] NVARCHAR(MAX),
    [BOLD] BIT,
    [CONTROLNAME] NVARCHAR(MAX),
    [FONTCOLOR] NVARCHAR(MAX),
    [VISIBLE] BIT,
    [UNDERLINE] BIT,
    [TRANSPARENT] BIT,
    [ICON] VARBINARY(MAX),
    [TEXTALIGN] NVARCHAR(MAX),
    [HASBORDER] BIT,
    [PARENTCONTROLNAME] NVARCHAR(MAX),
    [WIDTH] NVARCHAR(MAX),
    [ZINDEX] NVARCHAR(MAX),
    [FLAT] BIT,
    [REF1ID] INT,
    [REF2ID] INT,
    [FONTNAME] NVARCHAR(MAX),
    [IMAGEZOOM] NVARCHAR(MAX),
    [BORDERWIDTH] NVARCHAR(MAX),
    [BACKCOLOR] NVARCHAR(MAX),
    [HEIGHT] NVARCHAR(MAX),
    [ICONALIGN] NVARCHAR(MAX),
    [POSLEFT] NVARCHAR(MAX),
    [CUSTOMDATA1] NVARCHAR(MAX),
    [CUSTOMDATA2] NVARCHAR(MAX),
    [CUSTOMDATA3] NVARCHAR(MAX),
    [POSTOP] NVARCHAR(MAX),
    [CONTROLTYPE] NVARCHAR(MAX),
    [ANH] VARBINARY(MAX),
    [BUTTONSHAPE] NVARCHAR(MAX),
    [ROTATE] NVARCHAR(MAX),
    [NUMCHAIRS] NVARCHAR(MAX)
);
GO

-- Bảng: DBANGGIA
CREATE TABLE DBANGGIA (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [LOAIBANGGIA] DECIMAL(18,2),
    [COCUOITUAN] NVARCHAR(MAX),
    [CONGAYLE] DATETIME
);
GO

-- Bảng: DBANGGIACHITIET
CREATE TABLE DBANGGIACHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [DBANGGIAID] INT,
    [USERCREATEDID] INT,
    [TUGIO] DATETIME,
    [DENGIO] DATETIME,
    [SOTIEN] DECIMAL(18,2),
    [NGAYLE] DATETIME
);
GO

-- Bảng: DBANGGIATHEOBAN
CREATE TABLE DBANGGIATHEOBAN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [DBANID] INT,
    [USERCREATEDID] INT,
    [DBANGGIAID] INT
);
GO

-- Bảng: DBANGGIATHEOKHUVUC
CREATE TABLE DBANGGIATHEOKHUVUC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [DKHUVUCID] INT,
    [USERCREATEDID] INT,
    [DBANGGIAID] INT
);
GO

-- Bảng: DBANQUYEN
CREATE TABLE DBANQUYEN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [NGAYBATDAU] DATETIME,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DBIEUTUONG
CREATE TABLE DBIEUTUONG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [ANH] VARBINARY(MAX)
);
GO

-- Bảng: DCALAMVIEC
CREATE TABLE DCALAMVIEC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [TILELUONG] DECIMAL(18,2),
    [TUGIO] DATETIME,
    [DENGIO] DATETIME
);
GO

-- Bảng: DCHITIEUCHITIET
CREATE TABLE DCHITIEUCHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DCHITIEUDOANHTHUID] INT,
    [DTINHTHANHID] INT,
    [CHITIEU] DECIMAL(18,2)
);
GO

-- Bảng: DCHITIEUDOANHTHU
CREATE TABLE DCHITIEUDOANHTHU (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [DNHOMCHITIEUDOANHTHUID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [NAM] NVARCHAR(MAX),
    [THANG1] NVARCHAR(MAX),
    [THANG2] NVARCHAR(MAX),
    [THANG3] NVARCHAR(MAX),
    [THANG4] NVARCHAR(MAX),
    [THANG5] NVARCHAR(MAX),
    [THANG6] NVARCHAR(MAX),
    [THANG7] NVARCHAR(MAX),
    [THANG8] NVARCHAR(MAX),
    [THANG9] NVARCHAR(MAX),
    [THANG10] NVARCHAR(MAX),
    [THANG11] NVARCHAR(MAX),
    [THANG12] NVARCHAR(MAX)
);
GO

-- Bảng: DCUAHANG
CREATE TABLE DCUAHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [DIACHI] DECIMAL(18,2),
    [DIENTHOAI] NVARCHAR(MAX),
    [DKHOHANGID] INT,
    [STEMPLATEID] INT,
    [CODE] NVARCHAR(MAX)
);
GO

-- Bảng: DDINHLUONG
CREATE TABLE DDINHLUONG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DMATHANGID] INT,
    [SOLUONG] DECIMAL(18,2),
    [DVATTUID] INT
);
GO

-- Bảng: DDOITACKYGUI
CREATE TABLE DDOITACKYGUI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [HOAHONG] DECIMAL(18,2)
);
GO

-- Bảng: DDONVITINH
CREATE TABLE DDONVITINH (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DDOTKHUYENMAI
CREATE TABLE DDOTKHUYENMAI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DLOAIHINHKHUYENMAIID] INT,
    [TUNGAY] DATETIME,
    [DENNGAY] DATETIME,
    [NGUNGAPDUNG] NVARCHAR(MAX),
    [TILEGIAMGIA] DECIMAL(18,2),
    [TILEGIAMGIATIENGIO] DECIMAL(18,2),
    [KHUYENMAIGIOHAT] DATETIME,
    [TILEGIAMGIATONG] DECIMAL(18,2),
    [TUGIO] DATETIME,
    [DENGIO] DATETIME,
    [TILEGIAMGIAGIODAU] DECIMAL(18,2)
);
GO

-- Bảng: DDOTKHUYENMAICHITIET
CREATE TABLE DDOTKHUYENMAICHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DDOTKHUYENMAIID] INT,
    [DNHOMMATHANGID] INT,
    [TILEGIAMGIA] DECIMAL(18,2),
    [DMATHANGID] INT,
    [GIABAN] DECIMAL(18,2),
    [GIATRIDONHANG] DECIMAL(18,2),
    [SOLUONGMATHANG] DECIMAL(18,2),
    [SOLUONGMUA] DECIMAL(18,2),
    [SOLUONGTANG] DECIMAL(18,2),
    [DMATHANGTANGID] INT
);
GO

-- Bảng: DGHICHUPHACHE
CREATE TABLE DGHICHUPHACHE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DGIAMATHANG
CREATE TABLE DGIAMATHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DGIAODIENTHAOTAC
CREATE TABLE DGIAODIENTHAOTAC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DHANGSANXUAT
CREATE TABLE DHANGSANXUAT (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DKHACHHANG
CREATE TABLE DKHACHHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [DNHOMKHACHHANGID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [MAKHACH] NVARCHAR(MAX),
    [DIACHI] DECIMAL(18,2),
    [DIENTHOAI] NVARCHAR(MAX),
    [EMAIL] NVARCHAR(MAX),
    [MASOTHUE] DECIMAL(18,2),
    [DNHANVIENID] INT,
    [NGAYSINH] DATETIME,
    [DIEMTICHLUYBANDAU] DECIMAL(18,2),
    [GIABAN] DECIMAL(18,2),
    [DTINHTHANHID] INT,
    [FACEBOOK] NVARCHAR(MAX),
    [DTHETRATRUOCID] INT
);
GO

-- Bảng: DKHOHANG
CREATE TABLE DKHOHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [CHOPHEPAMKHO] NVARCHAR(MAX),
    [DCUAHANGID] INT
);
GO

-- Bảng: DKHUVUC
CREATE TABLE DKHUVUC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [STEMPLATEID] INT,
    [DKHOHANGID] INT,
    [TABHIENTHI] NVARCHAR(MAX),
    [DGIAMATHANGID] INT,
    [DBIEUTUONGID] INT,
    [TIENMOBAN] DECIMAL(18,2),
    [DGIATHEOGIOID] INT,
    [TUGIO] DATETIME,
    [DENGIO] DATETIME,
    [CACHTINHGIO] DATETIME,
    [DONGIA] DECIMAL(18,2),
    [DBANGGIAID] INT,
    [GRIDSIZE] NVARCHAR(MAX),
    [WIDTH] NVARCHAR(MAX),
    [HEIGHT] NVARCHAR(MAX),
    [BACKCOLOR] NVARCHAR(MAX),
    [BACKGROUNDIMAGE] VARBINARY(MAX),
    [MAUSAC] NVARCHAR(MAX),
    [ANH] VARBINARY(MAX)
);
GO

-- Bảng: DLOAIDO
CREATE TABLE DLOAIDO (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DLOAIHINHKHUYENMAI
CREATE TABLE DLOAIHINHKHUYENMAI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DLOAIMATHANG
CREATE TABLE DLOAIMATHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [COBANHANG] NVARCHAR(MAX),
    [COTONKHO] NVARCHAR(MAX),
    [CODINHLUONG] NVARCHAR(MAX)
);
GO

-- Bảng: DLOAIPHONG
CREATE TABLE DLOAIPHONG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [MAUCHU] NVARCHAR(MAX),
    [MAUNEN] NVARCHAR(MAX)
);
GO

-- Bảng: DLOAIQUY
CREATE TABLE DLOAIQUY (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DLYDOHUY
CREATE TABLE DLYDOHUY (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DLYDOTHUCHI
CREATE TABLE DLYDOTHUCHI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [LALYDOTHU] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [LOAILYDO] NVARCHAR(MAX)
);
GO

-- Bảng: DLYDOTHUONGPHAT
CREATE TABLE DLYDOTHUONGPHAT (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DMATHANG
CREATE TABLE DMATHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [CODE] NVARCHAR(MAX),
    [GIANHAP] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [GIABAN] DECIMAL(18,2),
    [GIABAN2] DECIMAL(18,2),
    [GIABAN3] DECIMAL(18,2),
    [GIABAN4] DECIMAL(18,2),
    [TONTOITHIEU] NVARCHAR(MAX),
    [TONTOIDA] NVARCHAR(MAX),
    [BAOHANH] NVARCHAR(MAX),
    [MASANCO] NVARCHAR(MAX),
    [DHANGSANXUATID] INT,
    [ANH] VARBINARY(MAX),
    [HOAHONG] DECIMAL(18,2),
    [GIAVON] DECIMAL(18,2),
    [DDONVITINHCHANID] INT,
    [GIABANCHAN] DECIMAL(18,2),
    [DDOITACKYGUIID] INT,
    [MACDINHGIAMGIA] DECIMAL(18,2),
    [MACDINHGIAMTIEN] DECIMAL(18,2),
    [DNHOMMATHANGID] INT,
    [DDONVITINHID] INT,
    [QUYDOI] NVARCHAR(MAX),
    [THEOCAN] NVARCHAR(MAX),
    [COHANSUDUNG] NVARCHAR(MAX),
    [SIZE] NVARCHAR(MAX),
    [TENTIENGANH] DECIMAL(18,2),
    [DLOAIMATHANGID] INT,
    [TAMKHOA] NVARCHAR(MAX),
    [GIATHEOTHOIGIA] DECIMAL(18,2),
    [MAUSAC] NVARCHAR(MAX)
);
GO

-- Bảng: DMATHANGMACDINH
CREATE TABLE DMATHANGMACDINH (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [DKHUVUCID] INT,
    [USERCREATEDID] INT,
    [DMATHANGID] INT,
    [SOLUONG] DECIMAL(18,2)
);
GO

-- Bảng: DMATKHAUWIFI
CREATE TABLE DMATKHAUWIFI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [DNHOMWIFIID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT
);
GO

-- Bảng: DMUCDICHDAT
CREATE TABLE DMUCDICHDAT (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DNHACUNGCAP
CREATE TABLE DNHACUNGCAP (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [DNHOMNHACUNGCAPID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [MANHACUNGCAP] NVARCHAR(MAX),
    [DIACHI] DECIMAL(18,2),
    [DIENTHOAI] NVARCHAR(MAX),
    [EMAIL] NVARCHAR(MAX),
    [WEBSITE] NVARCHAR(MAX)
);
GO

-- Bảng: DNHANVIEN
CREATE TABLE DNHANVIEN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [CACHTINHLUONG] NVARCHAR(MAX),
    [NGHITHU7] DECIMAL(18,2),
    [NGHICHUNHAT] NVARCHAR(MAX),
    [LUONGCA] NVARCHAR(MAX),
    [LUONGTHANG] NVARCHAR(MAX),
    [DIACHI] DECIMAL(18,2),
    [DIENTHOAI] NVARCHAR(MAX),
    [LUONGTHEOCA] NVARCHAR(MAX),
    [DCALAMVIECID] INT,
    [CODE] NVARCHAR(MAX)
);
GO

-- Bảng: DNHOMCHITIEUDOANHTHU
CREATE TABLE DNHOMCHITIEUDOANHTHU (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DNHOMHIENTHI
CREATE TABLE DNHOMHIENTHI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DNHOMKHACHHANG
CREATE TABLE DNHOMKHACHHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [TILEGIAMGIA] DECIMAL(18,2),
    [DIEMTICHLUY] DECIMAL(18,2),
    [TILEGIAMGIATIENHANG] DECIMAL(18,2),
    [TILEGIAMGIATIENGIO] DECIMAL(18,2),
    [TILEGIAMDOAN] DECIMAL(18,2),
    [TILEGIAMDOUONG] DECIMAL(18,2),
    [TILEGIAMDICHVU] DECIMAL(18,2),
    [TILEGIAMDOKHAC] DECIMAL(18,2)
);
GO

-- Bảng: DNHOMMATHANG
CREATE TABLE DNHOMMATHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [CODE] NVARCHAR(MAX),
    [DLOAIDOID] INT,
    [MAUSAC] NVARCHAR(MAX),
    [ANH] VARBINARY(MAX)
);
GO

-- Bảng: DNHOMNHACUNGCAP
CREATE TABLE DNHOMNHACUNGCAP (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DNHOMTHETRATRUOC
CREATE TABLE DNHOMTHETRATRUOC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DNHOMVOUCHER
CREATE TABLE DNHOMVOUCHER (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DNHOMWIFI
CREATE TABLE DNHOMWIFI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DPHUONGTHUCDAT
CREATE TABLE DPHUONGTHUCDAT (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DTAIKHOANNGANHANG
CREATE TABLE DTAIKHOANNGANHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DTHETRATRUOC
CREATE TABLE DTHETRATRUOC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [DNHOMTHETRATRUOCID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [KHOA] NVARCHAR(MAX),
    [NGAYHETHAN] DATETIME
);
GO

-- Bảng: DTINHTHANH
CREATE TABLE DTINHTHANH (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DTKTHEOKHUVUC
CREATE TABLE DTKTHEOKHUVUC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [DKHUVUCID] INT,
    [USERCREATEDID] INT,
    [SUSERID] INT
);
GO

-- Bảng: DTRANGTHAICHEBIEN
CREATE TABLE DTRANGTHAICHEBIEN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT
);
GO

-- Bảng: DUNGDUNG
CREATE TABLE DUNGDUNG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: DVOUCHER
CREATE TABLE DVOUCHER (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [DNHOMVOUCHERID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [GIATRI] DECIMAL(18,2),
    [NGAYPHATHANH] DATETIME,
    [HANSUDUNG] DATETIME,
    [DKHACHHANGID] INT
);
GO

-- Bảng: SANALYSIS
CREATE TABLE SANALYSIS (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [CONFIG] NVARCHAR(MAX),
    [ANALYSISTYPE] NVARCHAR(MAX),
    [COTTONG] NVARCHAR(MAX)
);
GO

-- Bảng: SCOLUMN
CREATE TABLE SCOLUMN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [STABLEDESCID] INT,
    [CAPTION] NVARCHAR(MAX),
    [FORMAT] NVARCHAR(MAX),
    [REFTABLEID] INT,
    [ALLOWEMPTY] NVARCHAR(MAX),
    [ALLOWDUPLICATE] NVARCHAR(MAX),
    [ISSYSTEM] BIT,
    [ENABLECONFIGID] INT,
    [TITLECONFIGID] INT,
    [TOOLTIP] NVARCHAR(MAX),
    [SFUNCTIONID] INT,
    [MAXVALUE] NVARCHAR(MAX),
    [MINVALUE] NVARCHAR(MAX),
    [DEFAULTCONFIGID] INT,
    [TAG] NVARCHAR(MAX),
    [CONTROLTYPE] NVARCHAR(MAX),
    [SHOWONLOOKUP] NVARCHAR(MAX),
    [FORMULA] NVARCHAR(MAX),
    [AUTOREPORT] NVARCHAR(MAX)
);
GO

-- Bảng: SCONFIG
CREATE TABLE SCONFIG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [TEXTVALUE] NVARCHAR(MAX),
    [DATETIMEVALUE] DATETIME,
    [INTVALUE] NVARCHAR(MAX),
    [DECIMALVALUE] NVARCHAR(MAX),
    [DATATYPE] NVARCHAR(MAX),
    [BLOBVALUE] VARBINARY(MAX),
    [CAPTION] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [SIMAGEID] INT,
    [MOREDETAIL] NVARCHAR(MAX),
    [CONTROLTYPE] NVARCHAR(MAX),
    [REFTABLEID] INT,
    [OTHERCONFIG] NVARCHAR(MAX),
    [SCONFIGGROUPID] INT,
    [TAB] NVARCHAR(MAX),
    [SOCOT] INT,
    [HEADER] NVARCHAR(MAX),
    [FOOTER] NVARCHAR(MAX),
    [SHOWONREPORT] NVARCHAR(MAX),
    [PARENTID] INT
);
GO

-- Bảng: SCONFIGGROUP
CREATE TABLE SCONFIGGROUP (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [IMAGE] VARBINARY(MAX),
    [MAUHOADON] NVARCHAR(MAX)
);
GO

-- Bảng: SFORM
CREATE TABLE SFORM (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [CODE] NVARCHAR(MAX),
    [DESIGNCODE] NVARCHAR(MAX),
    [FORMTYPE] NVARCHAR(MAX),
    [STABLEDESCID] INT,
    [NOTEMPLATE] NVARCHAR(MAX),
    [AELAYOUT] NVARCHAR(MAX),
    [LOAI] NVARCHAR(MAX),
    [IMAGE32] VARBINARY(MAX),
    [TABLEDESC] NVARCHAR(MAX),
    [LASTTEMPLATEID] INT,
    [CLASSNAME] NVARCHAR(MAX),
    [FILTERCONFIG] NVARCHAR(MAX),
    [REFCONFIG] NVARCHAR(MAX),
    [REPORTDESC] NVARCHAR(MAX),
    [SFUNCTIONID] INT,
    [SHOWTOTAL] NVARCHAR(MAX),
    [CLIENTCODE] NVARCHAR(MAX),
    [SERVERCODE] NVARCHAR(MAX),
    [TSCODE] NVARCHAR(MAX),
    [TSLAYOUT] NVARCHAR(MAX),
    [TSDESIGNCODE] NVARCHAR(MAX)
);
GO

-- Bảng: SFUNCTION
CREATE TABLE SFUNCTION (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [GROUPNAME] NVARCHAR(MAX),
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT
);
GO

-- Bảng: SGRID
CREATE TABLE SGRID (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [MOBILE] NVARCHAR(MAX),
    [GRIDID] INT
);
GO

-- Bảng: SGROUPROLE
CREATE TABLE SGROUPROLE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SGROUPUSERID] INT,
    [SFUNCTIONID] INT,
    [MODE] NVARCHAR(MAX)
);
GO

-- Bảng: SGROUPUSER
CREATE TABLE SGROUPUSER (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SIMAGEID] INT,
    [ITEMTYPE] NVARCHAR(MAX),
    [PARENTDIR] NVARCHAR(MAX),
    [PARENTID] INT,
    [SORTORDER] INT,
    [AUTOID] INT
);
GO

-- Bảng: SIMAGE
CREATE TABLE SIMAGE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [IMAGE] VARBINARY(MAX)
);
GO

-- Bảng: SMENU
CREATE TABLE SMENU (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [OPERATION] NVARCHAR(MAX),
    [STABLEDESCID] INT,
    [SFORMID] INT,
    [BOLD] BIT,
    [ITALIC] BIT,
    [IMAGE] VARBINARY(MAX),
    [TOOLBAR] NVARCHAR(MAX),
    [TOOLBARINDEX] NVARCHAR(MAX),
    [SHORTCUT] NVARCHAR(MAX),
    [TOOLBARTITLTE] NVARCHAR(MAX),
    [VISIBLECONFIGID] INT,
    [SREPORTID] INT,
    [VIEWCOUNT] INT,
    [SFUNCTIONID] INT,
    [LOAI] NVARCHAR(MAX),
    [LOCTHEOLOAI] NVARCHAR(MAX),
    [HIDEINMENU] NVARCHAR(MAX),
    [MENUCODE] NVARCHAR(MAX),
    [VIEWONTS] NVARCHAR(MAX),
    [VIEWONMOBI] NVARCHAR(MAX),
    [VIEWONWEB] NVARCHAR(MAX)
);
GO

-- Bảng: SQUICKNOTE
CREATE TABLE SQUICKNOTE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [NOTEDATA] NVARCHAR(MAX)
);
GO

-- Bảng: SREPORT
CREATE TABLE SREPORT (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [IMAGE32] VARBINARY(MAX),
    [FILTERCONFIG] NVARCHAR(MAX),
    [VERTICALLAYOUT] NVARCHAR(MAX),
    [RUNCOUNT] NVARCHAR(MAX),
    [MASTERVIEW] NVARCHAR(MAX),
    [DETAILVIEW] NVARCHAR(MAX),
    [HASDETAIL] BIT,
    [FILTERONTOP] NVARCHAR(MAX),
    [HASDETAIL2] BIT,
    [DETAIL2VIEW] NVARCHAR(MAX),
    [VIEWINREPORTMG] NVARCHAR(MAX),
    [SQL] NVARCHAR(MAX),
    [PARAMS] NVARCHAR(MAX),
    [LASTTEMPLATEID] INT,
    [SQLMODE] NVARCHAR(MAX),
    [REMINDER] NVARCHAR(MAX),
    [FORMAT] NVARCHAR(MAX),
    [THUONGDUNG] DECIMAL(18,2),
    [CODE] NVARCHAR(MAX),
    [COLCONFIG] NVARCHAR(MAX),
    [RAWMODE] NVARCHAR(MAX),
    [CLASSNAME] NVARCHAR(MAX),
    [SERVERCODE] NVARCHAR(MAX),
    [CLIENTCODE] NVARCHAR(MAX)
);
GO

-- Bảng: SREPORTROLE
CREATE TABLE SREPORTROLE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [STATUS] BIT DEFAULT 1,
    [MODE] NVARCHAR(MAX),
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERMODIFIEDID] INT,
    [USERCREATEDID] INT,
    [SGROUPUSERID] INT,
    [SREPORTID] INT
);
GO

-- Bảng: SREPORTTEMPLATE
CREATE TABLE SREPORTTEMPLATE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [TEMPLATE] NVARCHAR(MAX),
    [STEMPLATEID] INT,
    [SREPORTID] INT,
    [CONFIG] NVARCHAR(MAX),
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [AUTOGENREPORT] NVARCHAR(MAX),
    [COLAUTOWIDTH] NVARCHAR(MAX),
    [STEMPLATELANDSCAPEID] INT
);
GO

-- Bảng: SSMSTEMPLATE
CREATE TABLE SSMSTEMPLATE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [AUTOID] INT,
    [STATUS] BIT DEFAULT 1,
    [ITEMTYPE] NVARCHAR(MAX),
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [USERMODIFIEDID] INT,
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [SIMAGEID] INT
);
GO

-- Bảng: STABLEDESC
CREATE TABLE STABLEDESC (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DEFAULTID] INT,
    [SORTBY] NVARCHAR(MAX),
    [DESCRIPTION] NVARCHAR(MAX),
    [TABLETYPE] NVARCHAR(MAX),
    [COTTANG] NVARCHAR(MAX),
    [COTGIAM] DECIMAL(18,2),
    [SFUNCTIONID] INT,
    [AELAYOUT] NVARCHAR(MAX),
    [SORTORDER] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [ISSYSTEM] BIT,
    [USEDEFAULTAEFORM] NVARCHAR(MAX),
    [GENNO] NVARCHAR(MAX),
    [NOTEMPLATE] NVARCHAR(MAX),
    [IMAGE32] VARBINARY(MAX),
    [IMAGE] VARBINARY(MAX),
    [CODE] NVARCHAR(MAX),
    [DESIGNCODE] NVARCHAR(MAX),
    [CATEGORYCOL] NVARCHAR(MAX),
    [FILTERCONFIG] NVARCHAR(MAX),
    [INVOICEPARAM] NVARCHAR(MAX),
    [INVOICEDETAILPARAM] NVARCHAR(MAX),
    [INVOICEPRINT] NVARCHAR(MAX),
    [BARCODEPRINT] NVARCHAR(MAX),
    [LASTTEMPLATEID] INT,
    [MUSTSELECTCATEGORY] NVARCHAR(MAX),
    [MASTERTABLEID] INT,
    [FORMAT] NVARCHAR(MAX),
    [REFCONFIG] NVARCHAR(MAX),
    [AUTOREPORT] NVARCHAR(MAX),
    [SHOWTOTAL] NVARCHAR(MAX),
    [READONLY] NVARCHAR(MAX),
    [CLIENTCODE] NVARCHAR(MAX),
    [SERVERCODE] NVARCHAR(MAX),
    [SYNCOPTION] NVARCHAR(MAX),
    [TSCODE] NVARCHAR(MAX),
    [TSLAYOUT] NVARCHAR(MAX),
    [TSDESIGNCODE] NVARCHAR(MAX)
);
GO

-- Bảng: STEMPLATE
CREATE TABLE STEMPLATE (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [SORTORDER] INT,
    [USERCREATEDID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [ITEMTYPE] NVARCHAR(MAX),
    [AUTOID] INT,
    [SIMAGEID] INT,
    [TEMPLATE] NVARCHAR(MAX),
    [STABLEDESCID] INT,
    [REPORTBASE] NVARCHAR(MAX),
    [SFORMID] INT,
    [BARCODE] NVARCHAR(MAX),
    [BARCODECOL] NVARCHAR(MAX),
    [STYLE] NVARCHAR(MAX)
);
GO

-- Bảng: SUSER
CREATE TABLE SUSER (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [PASSWORD] NVARCHAR(MAX),
    [USERNAME] NVARCHAR(MAX),
    [EMAIL] NVARCHAR(MAX),
    [ISADMIN] BIT,
    [SGROUPUSERID] INT,
    [SMTP] NVARCHAR(MAX),
    [SSL] NVARCHAR(MAX),
    [PORT] INT,
    [PASS] NVARCHAR(MAX),
    [VIETINPUT] NVARCHAR(MAX),
    [INPUTMODE] NVARCHAR(MAX),
    [SIMAGEID] INT,
    [AUTOID] INT,
    [PARENTID] INT,
    [PARENTDIR] NVARCHAR(MAX),
    [SORTORDER] INT,
    [ITEMTYPE] NVARCHAR(MAX),
    [DNHANVIENID] INT,
    [DEFAULTFUNCID] INT,
    [USERID] INT,
    [CARDCODE] NVARCHAR(MAX)
);
GO

-- Bảng: TBANGLUONG
CREATE TABLE TBANGLUONG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [THANG] NVARCHAR(MAX),
    [NAM] NVARCHAR(MAX),
    [CHITIET] DECIMAL(18,2)
);
GO

-- Bảng: TBANGLUONGCHITIET
CREATE TABLE TBANGLUONGCHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [TBANGLUONGID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DNHANVIENID] INT,
    [DCALAMVIECID] INT,
    [TRANGTHAI] NVARCHAR(MAX),
    [NGAY] DATETIME
);
GO

-- Bảng: TBANGLUONGTONGHOP
CREATE TABLE TBANGLUONGTONGHOP (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DNHANVIENID] INT,
    [LUONGCA] NVARCHAR(MAX),
    [TONGLUONG] NVARCHAR(MAX),
    [PHAT] NVARCHAR(MAX),
    [TAMUNG] NVARCHAR(MAX),
    [THUCNHAN] DECIMAL(18,2),
    [THUONG] DECIMAL(18,2),
    [LUONGTHANG] NVARCHAR(MAX),
    [CACHTINHLUONG] NVARCHAR(MAX),
    [TBANGLUONGID] INT,
    [SOGIOLAM] DATETIME,
    [SOGIOTANGCA] DATETIME,
    [LUONGTHEOCA] NVARCHAR(MAX)
);
GO

-- Bảng: TBAOGIA
CREATE TABLE TBAOGIA (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [NGAY] DATETIME,
    [TENKHACH] NVARCHAR(MAX),
    [DIACHI] DECIMAL(18,2),
    [DIENTHOAI] NVARCHAR(MAX),
    [EMAIL] NVARCHAR(MAX),
    [TIENHANG] DECIMAL(18,2),
    [TILETHUE] DECIMAL(18,2),
    [TIENTHUE] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [TIENGIAMGIA] DECIMAL(18,2),
    [PHIVANCHUYEN] NVARCHAR(MAX),
    [TONGCONG] NVARCHAR(MAX),
    [LOAI] NVARCHAR(MAX),
    [GIAMTHEOTIEN] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DKHACHHANGID] INT
);
GO

-- Bảng: TBAOGIACHITIET
CREATE TABLE TBAOGIACHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [SOLUONG] DECIMAL(18,2),
    [DONGIA] DECIMAL(18,2),
    [THANHTIEN] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DDONVITINHID] INT,
    [TBAOGIAID] INT,
    [DMATHANGID] INT
);
GO

-- Bảng: TCHITIETTHANHTOAN
CREATE TABLE TCHITIETTHANHTOAN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [TDONHANGID] INT,
    [TTHUCHIID] INT,
    [SOTIEN] DECIMAL(18,2)
);
GO

-- Bảng: TDATHANG
CREATE TABLE TDATHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [NGAY] DATETIME,
    [TENKHACH] NVARCHAR(MAX),
    [DIACHI] DECIMAL(18,2),
    [DIENTHOAI] NVARCHAR(MAX),
    [EMAIL] NVARCHAR(MAX),
    [TIENHANG] DECIMAL(18,2),
    [TILETHUE] DECIMAL(18,2),
    [TIENTHUE] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [TIENGIAMGIA] DECIMAL(18,2),
    [PHIVANCHUYEN] NVARCHAR(MAX),
    [TONGCONG] NVARCHAR(MAX),
    [LOAI] NVARCHAR(MAX),
    [GIAMTHEOTIEN] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DKHACHHANGID] INT,
    [LOAIGIA] DECIMAL(18,2),
    [DPHUONGTHUCDATID] INT,
    [DMUCDICHDATID] INT,
    [TUGIO] DATETIME,
    [DENGIO] DATETIME,
    [TUNGAY] DATETIME,
    [DENNGAY] DATETIME,
    [GIODAT] DATETIME,
    [MAUSAC] NVARCHAR(MAX),
    [DBANID] INT,
    [GUID] INT
);
GO

-- Bảng: TDATHANGCHITIET
CREATE TABLE TDATHANGCHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [SOLUONG] DECIMAL(18,2),
    [DONGIA] DECIMAL(18,2),
    [THANHTIEN] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [BAOHANH] NVARCHAR(MAX),
    [DDONVITINHID] INT,
    [TDATHANGID] INT,
    [DMATHANGID] INT
);
GO

-- Bảng: TDONHANG
CREATE TABLE TDONHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [GIAMTHEOTIEN] DECIMAL(18,2),
    [LOAI] NVARCHAR(MAX),
    [TONGCONG] NVARCHAR(MAX),
    [PHIVANCHUYEN] NVARCHAR(MAX),
    [TIENGIAMGIA] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [TIENTHUE] DECIMAL(18,2),
    [TILETHUE] DECIMAL(18,2),
    [TIENHANG] DECIMAL(18,2),
    [DNHACUNGCAPID] INT,
    [DKHOXUATID] INT,
    [DKHONHAPID] INT,
    [DNHANVIENXUATID] INT,
    [DNHANVIENNHAPID] INT,
    [DIENGIAI] DECIMAL(18,2),
    [GIOTHANHTOAN] DATETIME,
    [KHACHDUA] NVARCHAR(MAX),
    [TRALAI] NVARCHAR(MAX),
    [NOCU] NVARCHAR(MAX),
    [LOAIGIA] DECIMAL(18,2),
    [USERTHANHTOANID] INT,
    [TIENTHANHTOAN] DECIMAL(18,2),
    [LOAITHANHTOAN] NVARCHAR(MAX),
    [TDATHANGID] INT,
    [GIAOHANG] DECIMAL(18,2),
    [DATHANHTOAN] NVARCHAR(MAX),
    [DOITRA] NVARCHAR(MAX),
    [CONNO] NVARCHAR(MAX),
    [DIEM] DECIMAL(18,2),
    [VOUCHER] NVARCHAR(MAX),
    [DNHANVIENGIAOID] INT,
    [TRICHNHANVIEN] NVARCHAR(MAX),
    [DCUAHANGID] INT,
    [CONLAI] NVARCHAR(MAX),
    [THANHTOAN] NVARCHAR(MAX),
    [DKHACHHANGID] INT,
    [DTAIKHOANNGANHANGID] INT,
    [DVOUCHERID] INT,
    [THETRATRUOC] NVARCHAR(MAX),
    [DTHETRATRUOCID] INT,
    [TRUTICHLUY] NVARCHAR(MAX),
    [DIEMGIAM] DECIMAL(18,2),
    [TIENMAT] DECIMAL(18,2),
    [CHUYENKHOAN] NVARCHAR(MAX),
    [THE] NVARCHAR(MAX),
    [DBANID] INT,
    [BATDAU] DATETIME,
    [KETTHUC] DECIMAL(18,2),
    [NHOMGUID] INT,
    [TIENGIO] DECIMAL(18,2),
    [TILEGIAMGIAGIO] DECIMAL(18,2),
    [TIENGIAMGIAGIO] DECIMAL(18,2),
    [SOKHACH] NVARCHAR(MAX),
    [PHIDICHVU] NVARCHAR(MAX),
    [TILEPHIDICHVU] DECIMAL(18,2),
    [TILEGIAMGIATONG] DECIMAL(18,2),
    [TIENGIAMGIATONG] DECIMAL(18,2),
    [GIAMGIAGIOTHEOTIEN] DECIMAL(18,2),
    [PHIDICHVUTHEOTIEN] DECIMAL(18,2),
    [GIAMTONGTHEOTIEN] DECIMAL(18,2),
    [SOORDER] NVARCHAR(MAX),
    [TUTHAYDOIGIO] DATETIME,
    [SOHD] NVARCHAR(MAX),
    [SOTT] NVARCHAR(MAX),
    [SOLANINTAMTINH] NVARCHAR(MAX),
    [DONGIA] DECIMAL(18,2),
    [DBANGGIAID] INT,
    [TIENGIOPHONGCUOI] DECIMAL(18,2),
    [BATDAUPHONGCUOI] NVARCHAR(MAX),
    [CACHTINHGIA] DECIMAL(18,2),
    [TIENMOBAN] DECIMAL(18,2),
    [LANINHOADON] NVARCHAR(MAX),
    [INTAMTINHLUC] NVARCHAR(MAX),
    [DATTRUOC] NVARCHAR(MAX),
    [CONGNO] NVARCHAR(MAX),
    [TIENHANGCHUAGIAM] DECIMAL(18,2),
    [GIAMGIAMATHANG] DECIMAL(18,2),
    [PHUTKHUYENMAI] NVARCHAR(MAX),
    [TILEKHUYENMAIPHUTDAU] DECIMAL(18,2),
    [PASSWIFI] NVARCHAR(MAX)
);
GO

-- Bảng: TDONHANGCHITIET
CREATE TABLE TDONHANGCHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [TDONHANGID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DMATHANGID] INT,
    [BAOHANH] NVARCHAR(MAX),
    [TILEGIAMGIA] DECIMAL(18,2),
    [THANHTIEN] DECIMAL(18,2),
    [DONGIA] DECIMAL(18,2),
    [SLNHAP] NVARCHAR(MAX),
    [SLXUAT] NVARCHAR(MAX),
    [SLTHUCTE] DECIMAL(18,2),
    [SLHETHONG] NVARCHAR(MAX),
    [DKHOHANGID] INT,
    [KHUYENMAI] NVARCHAR(MAX),
    [DDONVITINHID] INT,
    [SLNHAPCHUAQUYDOI] NVARCHAR(MAX),
    [SLXUATCHUAQUYDOI] NVARCHAR(MAX),
    [GIAMTHEOTIEN] DECIMAL(18,2),
    [TIENGIAMGIA] DECIMAL(18,2),
    [TDONHANGTRAID] INT,
    [XUATVATTU] NVARCHAR(MAX),
    [KICHTHUOC] DECIMAL(18,2),
    [HANSUDUNG] DATETIME,
    [DNHANVIEN1ID] INT,
    [DNHANVIEN2ID] INT,
    [DNHANVIEN3ID] INT,
    [TENHANG] NVARCHAR(MAX),
    [TUGIO] DATETIME,
    [DENGIO] DATETIME,
    [GIAVON] DECIMAL(18,2),
    [COMBOID] INT,
    [COMBOPARENTID] INT,
    [COMBOSL] NVARCHAR(MAX),
    [DTRANGTHAICHEBIENID] INT,
    [GIOTINHLUONG] DATETIME
);
GO

-- Bảng: TDONHANGGIO
CREATE TABLE TDONHANGGIO (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [TDONHANGID] INT,
    [USERCREATEDID] INT,
    [TUGIO] DATETIME,
    [DENGIO] DATETIME,
    [DONGIA] DECIMAL(18,2),
    [DBANGGIAID] INT,
    [DBANID] INT,
    [THANHTIEN] DECIMAL(18,2),
    [CACHTINHGIA] DECIMAL(18,2)
);
GO

-- Bảng: TDONHANGHUY
CREATE TABLE TDONHANGHUY (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [KHACHHANG] NVARCHAR(MAX),
    [NHANVEN] NVARCHAR(MAX),
    [THUNGAN] DECIMAL(18,2),
    [DOITRA] NVARCHAR(MAX),
    [DATHANHTOAN] NVARCHAR(MAX),
    [GIOTHANHTOAN] DATETIME,
    [TRALAI] NVARCHAR(MAX),
    [TIENHANG] DECIMAL(18,2),
    [TILETHUE] DECIMAL(18,2),
    [TIENTHUE] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [TIENGIAMGIA] DECIMAL(18,2),
    [PHIVANCHUYEN] NVARCHAR(MAX),
    [THANHTOANBOI] NVARCHAR(MAX),
    [NGAYHUY] DATETIME,
    [GIOHUY] DATETIME,
    [TDONHANGID] INT,
    [LYDOHUY] NVARCHAR(MAX),
    [TIENGIO] DECIMAL(18,2),
    [PHIDICHVU] NVARCHAR(MAX),
    [BAN] NVARCHAR(MAX)
);
GO

-- Bảng: TDONHANGHUYCHITIET
CREATE TABLE TDONHANGHUYCHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [TDONHANGHUYID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [MAHANG] NVARCHAR(MAX),
    [TENHANG] NVARCHAR(MAX),
    [DVT] NVARCHAR(MAX),
    [DONGIA] DECIMAL(18,2),
    [THANHTIEN] DECIMAL(18,2),
    [SOLUONG] DECIMAL(18,2)
);
GO

-- Bảng: TINCHEBIEN
CREATE TABLE TINCHEBIEN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [TDONHANGID] INT,
    [USERCREATEDID] INT,
    [LANSO] NVARCHAR(MAX),
    [TENHANG] NVARCHAR(MAX),
    [DLOAIDOID] INT,
    [DDONVITINHID] INT,
    [SOLUONG] DECIMAL(18,2)
);
GO

-- Bảng: TLUUTAM
CREATE TABLE TLUUTAM (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [DOITRA] NVARCHAR(MAX),
    [GIAOHANG] DECIMAL(18,2),
    [TDATHANGID] INT,
    [LOAIGIA] DECIMAL(18,2),
    [DIENGIAI] DECIMAL(18,2),
    [DNHANVIENXUATID] INT,
    [DKHOXUATID] INT,
    [TIENHANG] DECIMAL(18,2),
    [TILETHUE] DECIMAL(18,2),
    [TIENTHUE] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [TIENGIAMGIA] DECIMAL(18,2),
    [PHIVANCHUYEN] NVARCHAR(MAX),
    [TONGCONG] NVARCHAR(MAX),
    [GIAMTHEOTIEN] DECIMAL(18,2),
    [DKHACHHANGID] INT
);
GO

-- Bảng: TLUUTAMCHITIET
CREATE TABLE TLUUTAMCHITIET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [TLUUTAMID] INT,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SOLUONG] DECIMAL(18,2),
    [DONGIA] DECIMAL(18,2),
    [THANHTIEN] DECIMAL(18,2),
    [TILEGIAMGIA] DECIMAL(18,2),
    [BAOHANH] NVARCHAR(MAX),
    [DMATHANGID] INT,
    [SOLUONGCHUAQUYDOI] DECIMAL(18,2),
    [DDONVITINHID] INT
);
GO

-- Bảng: TLUUVET
CREATE TABLE TLUUVET (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [GIO] DATETIME,
    [SODONHANG] NVARCHAR(MAX),
    [TAIKHOAN] NVARCHAR(MAX),
    [THIETBI] NVARCHAR(MAX),
    [PHANLOAI] NVARCHAR(MAX),
    [BAN] NVARCHAR(MAX),
    [CHUCNANG] NVARCHAR(MAX),
    [SOLUONG] DECIMAL(18,2),
    [DONGIA] DECIMAL(18,2),
    [THANHTIEN] DECIMAL(18,2),
    [TENHANG] NVARCHAR(MAX)
);
GO

-- Bảng: TNGUOIDUNGTHEOCUAHANG
CREATE TABLE TNGUOIDUNGTHEOCUAHANG (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [SUSERID] INT,
    [DCUAHANGID] INT
);
GO

-- Bảng: TSOHOADON
CREATE TABLE TSOHOADON (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [SO] NVARCHAR(MAX)
);
GO

-- Bảng: TSOINCHEBIEN
CREATE TABLE TSOINCHEBIEN (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [SOLANIN] NVARCHAR(MAX),
    [MAYIN] NVARCHAR(MAX)
);
GO

-- Bảng: TSUACHUA
CREATE TABLE TSUACHUA (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [DBANID] INT,
    [DASUAXONG] NVARCHAR(MAX),
    [NOIDUNG] NVARCHAR(MAX),
    [DLOAIPHONGID] INT,
    [DNHANVIENID] INT,
    [CONSUDUNGDUOC] NVARCHAR(MAX)
);
GO

-- Bảng: TTANGGIAMDIEM
CREATE TABLE TTANGGIAMDIEM (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [DKHACHHANGID] INT,
    [DIEMTANG] DECIMAL(18,2),
    [DIEMGIAM] DECIMAL(18,2),
    [LYDO] NVARCHAR(MAX)
);
GO

-- Bảng: TTHUCHI
CREATE TABLE TTHUCHI (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [NGAY] DATETIME,
    [TENDOITUONG] NVARCHAR(MAX),
    [DIACHI] DECIMAL(18,2),
    [LOAI] NVARCHAR(MAX),
    [LOAIDOITUONG] NVARCHAR(MAX),
    [DIENGIAI] DECIMAL(18,2),
    [CHUNGTUGOC] NVARCHAR(MAX),
    [THU] DECIMAL(18,2),
    [CHI] DECIMAL(18,2),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [DNHACUNGCAPID] INT,
    [CHUYENKHOAN] NVARCHAR(MAX),
    [LATAMUNG] NVARCHAR(MAX),
    [TBANGLUONGID] INT,
    [TDATHANGID] INT,
    [DCUAHANGID] INT,
    [LAPHIEUTHUCONGNO] DECIMAL(18,2),
    [KHONGTHAYDOICONGNO] NVARCHAR(MAX),
    [DNHANVIENID] INT,
    [DKHACHHANGID] INT,
    [DLYDOTHUCHIID] INT,
    [DTAIKHOANNGANHANGID] INT,
    [DTHETRATRUOCID] INT,
    [TDONHANGID] INT
);
GO

-- Bảng: TTHUONGPHAT
CREATE TABLE TTHUONGPHAT (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NAME] NVARCHAR(MAX),
    [NOTE] NVARCHAR(MAX),
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [NGAY] DATETIME,
    [USERCREATEDID] INT,
    [DNHANVIENID] INT,
    [THUONG] DECIMAL(18,2),
    [PHAT] NVARCHAR(MAX),
    [DLYDOTHUONGPHATID] INT
);
GO

-- Bảng: TVAORA
CREATE TABLE TVAORA (
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [NOTE] NVARCHAR(MAX),
    [TBANGLUONGID] INT,
    [NGAY] DATETIME,
    [DNHANVIENID] INT,
    [GIOVAO] DATETIME,
    [GIORA] DATETIME,
    [SOGIO] DATETIME,
    [SOGIOTANGCA] DATETIME,
    [STATUS] BIT DEFAULT 1,
    [USERMODIFIEDID] INT,
    [TIMEMODIFIED] DATETIME,
    [TIMECREATED] DATETIME DEFAULT GETDATE(),
    [USERCREATEDID] INT,
    [GIOBATDAU] DATETIME,
    [GIOKETTHUC] DECIMAL(18,2)
);
GO

PRINT N'✅ Đã tạo thành công 98 bảng!';
GO
